### ISSUE TITLE
Troubles collecting events from SysMon

### ISSUE THREAD

**Issue by dzonespy** [wazuh/wazuh-ruleset#282]
Hello guys,
i'm trying to work through wazuh + sysmon to deeply monitor some Windows 10 installations. 

This is my configuration:

Client:

> Sysmon v8.04 (Sysmon schemaversion="4.00")
> Latest Wazuh Windows Agent

Server/Manager:

> App version: 3.8.2

> Content of /var/ossec/etc/rules/local_rules.xml
        \<group name="sysmon,">
         \<rule id="255000" level="12">
         \<if_group>sysmon_event1\</if_group>
         \<field name="sysmon.image">\\powershell.exe||\\.ps1||\\.ps2\</field>
         \<description>Sysmon - Event 1: Bad exe: $(sysmon.image)\</description>
         \<group>sysmon_event1,powershell_execution,\</group>
         \</rule>
         \</group>

> Content of /var/ossec/etc/shared/default/agent.conf
        \<agent_config os="Windows">
        \<localfile>
        \<location>Microsoft-Windows-Sysmon/Operational\</location>
        \<log_format>eventchannel\</log_format>
        \</localfile>
        \</agent_config>

> latest rulset available

The problem is i can see the log coming to /var/ossec/logs/archives/archives.json but they never meet /var/ossec/logs/alerts/alerts.json. No way to get them on dashboard.
This is a frame of what i get in  /var/ossec/logs/archives/archives.json triggering a powershell execution:

{"timestamp":"2019-02-05T19:57:29.782+0000","agent":{"id":"001","name":"Test-PC"},"manager":{"name":"dashboard.test.com"},"id":"1549472249.1100687","full_log":"{\"EventChannel\":{\"System\":{\"ProviderName\":\"Microsoft-Windows-Sysmon\",\"ProviderGuid\":\"{348S78F-C22A-43E0-BF4C-0690890}\",\"EventID\":\"1\",\"Version\":\"5\",\"Level\":\"4\",\"Task\":\"1\",\"Opcode\":\"0\",\"Keywords\":\"0x8000000000000000\",\"SystemTime\":\"2019-02-05T19:57:31.245937500Z\",\"EventRecordID\":\"2853\",\"ProcessID\":\"3748\",\"ThreadID\":\"10972\",\"Channel\":\"Microsoft-Windows-Sysmon/Operational\",\"Computer\":\"TEST-PC-01\",\"SeverityValue\":\"INFORMATION\",\"Message\":\"Process Create:\"},\"EventData\":{\"RuleName\":\"\",\"UtcTime\":\"2019-02-05 19:57:31.240\",\"ProcessGuid\":\"{2A19F121-11FB-5C5B-0000-0010C89B7B02}\",\"ProcessId\":\"4360\",\"Image\":\"C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe\",\"FileVersion\":\"10.0.17134.582 (WinBuild.160101.0800)\",\"Description\":\"Windows PowerShell\",\"Product\":\"Windows Operating System®\",\"Company\":\"Microsoft Corporation\",\"CommandLine\":\"\\\\\\\"C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe\\\\\\\"\",\"CurrentDirectory\":\"C:\\\\Users\\\\Emanuele\\\\\",\"User\":\"TEST-PC-01\\\\Test\",\"LogonGuid\":\"{1B23F021-E58E-5A5A-0000-0020BBA10200}\",\"LogonId\":\"0x2a2bb\",\"TerminalSessionId\":\"1\",\"IntegrityLevel\":\"Medium\",\"Hashes\":\"SHA1=1B3B40FBC889FD4C645CC12C85D0805AC36BA254,MD5=95000560239032BC68B4C2FDFCDEF913,SHA256=D3F8FADE829D2B7BD596C4504A6DAE5C034E789B6A3DEFBE013BDA7D14466677,IMPHASH=741776AACCFC5B71FF59832DCDCACE0F\",\"ParentProcessGuid\":\"{2B19F021-C58F-5C5A-0000-001026A50400}\",\"ParentProcessId\":\"4960\",\"ParentImage\":\"C:\\\\Windows\\\\explorer.exe\",\"ParentCommandLine\":\"C:\\\\Windows\\\\Explorer.EXE\"}}}","decoder":{"name":"windows_eventchannel"},"data":{"EventChannel":{"System":{"ProviderName":"Microsoft-Windows-Sysmon","ProviderGuid":"........................

As said, this never met alerts.json and i have no way to get this on dashboard. 
I followed the procedure described here -> 

https://wazuh.com/blog/using-wazuh-to-monitor-sysmon-events/

without being able to see any events from sysmon in dashboard.
Any help will be really appreciated.
Thank you.

**Comment by chemamartinez** [comment]
Hi @dzonespy,

I am afraid that blog entrance is outdated due to it has been changed the Eventchannel reader for Wazuh v3.8.0.

On this new version, we have improved the way we extract data from Windows Eventchannel, being able now to collect 10x more fields and data, we are extracting all the available fields and parsing all of them to JSON, later, on manager side, we can use dynamic fields to enrich alert descriptions and alert data.

You can read more information about this new feature in release notes: https://documentation.wazuh.com/current/release-notes/release_3_8_0.html#wazuh-core

Since the decoder extracts fields from the JSON dynamically, the field you are looking for (`sysmon.image`) doesn't longer exist. Its equivalent field regarding your event is `EventChannel.EventData.Image` so the rule should look for that new file as follows:

```
<group name="sysmon,">
  <rule id="255000" level="12">
     <if_group>sysmon_event1</if_group>
     <field name="EventChannel.EventData.Image">\powershell.exe||\.ps1||\.ps2</field>
     <description>Sysmon - Event 1: Bad exe: $(EventChannel.EventData.Image)</description>
     <group>sysmon_event1,powershell_execution,</group>
  </rule>
</group>
```

I already opened a ticket (https://github.com/wazuh/wazuh-ruleset/issues/284) to adapt current Sysmon rules to that new format.

Best regards,
Chema.

**Comment by dzonespy** [comment]
Hello @chemamartinez,
i thank you very much for your support !! I was guessing a problem like that. Anyway, I went on doing some more tests. Now i have the logs realted to a powershell Process Create event under 
/var/ossec/logs/archives/archives.json

`{"timestamp":"2019-02-07T11:57:53.720+0000","agent":{"id":"001","name":"[redacted]"},"manager":{"name":"[redacted]"},"id":"1549540673.566372","full_log":"{\"EventChannel\":{\"System\":{\"ProviderName\":\"Microsoft-Windows-Sysmon\",\"ProviderGuid\":\"{5770385F-C22A-43E0-BF4C-06F5698FFBD9}\",\"EventID\":\"1\",\"Version\":\"5\",\"Level\":\"4\",\"Task\":\"1\",\"Opcode\":\"0\",\"Keywords\":\"0x8000000000000000\",\"SystemTime\":\"2019-02-07T11:57:53.526042500Z\",\"EventRecordID\":\"8378\",\"ProcessID\":\"3748\",\"ThreadID\":\"10972\",\"Channel\":\"Microsoft-Windows-Sysmon/Operational\",\"Computer\":\"[redacted]\",\"SeverityValue\":\"INFORMATION\",\"Message\":\"Process Create:\"},\"EventData\":{\"RuleName\":\"\",\"UtcTime\":\"2019-02-07 11:57:53.521\",\"ProcessGuid\":\"{2B19F021-1D41-5C5C-0000-001002677B04}\",\"ProcessId\":\"18028\",\"Image\":\"C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe\",\"FileVersion\":\"10.0.17134.582 (WinBuild.160101.0800)\",\"Description\":\"Windows PowerShell\",\"Product\":\"Sistema operativo Microsoft® Windows®\",\"Company\":\"Microsoft Corporation\",\"CommandLine\":\"\\\\\\\"C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe\\\\\\\"\",\"CurrentDirectory\":\"C:\\\\Users\\\\redacted\\\\\",\"User\":\"[redacted]\\\\[redacted]\",\"LogonGuid\":\"{2B19F021-C58E-5C5A-0000-0020BBA20200}\",\"LogonId\":\"0x2a2bb\",\"TerminalSessionId\":\"1\",\"IntegrityLevel\":\"Medium\",\"Hashes\":\"SHA1=1B3B40FBC889FD4C645CC12C85D0805AC36BA254,MD5=95000560239032BC68B4C2FDFCDEF913,SHA256=D3F8FADE829D2B7BD596C4504A6DAE5C034E789B6A3DEFBE013BDA7D14466677,IMPHASH=741776AACCFC5B71FF59832DCDCACE0F\",\"ParentProcessGuid\":\"{2B19F021-C58F-5C5A-0000-001026A50400}\",\"ParentProcessId\":\"4960\",\"ParentImage\":\"C:\\\\Windows\\\\explorer.exe\",\"ParentCommandLine\":\"C:\\\\Windows\\\\Explorer.EXE\"}}}","decoder":{"name":"windows_eventchannel"},"data":{"EventChannel":{"System":{"ProviderName":"Microsoft-Windows-Sysmon","ProviderGuid":"{5770385F-C22A-43E0-BF4C-06F5698FFBD9}","EventID":"1","Version":"5","Level":"4","Task":"1","Opcode":"0","Keywords":"0x8000000000000000","SystemTime":"2019-02-07T11:57:53.526042500Z","EventRecordID":"8378","ProcessID":"3748","ThreadID":"10972","Channel":"Microsoft-Windows-Sysmon/Operational","Computer":"[redacted]","SeverityValue":"INFORMATION","Message":"Process Create:"},"EventData":{"UtcTime":"2019-02-07 11:57:53.521","ProcessGuid":"{2B19F021-1D41-5C5C-0000-001002677B04}","ProcessId":"18028","Image":"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe","FileVersion":"10.0.17134.582 (WinBuild.160101.0800)","Description":"Windows PowerShell","Product":"Microsoft Windows Operating System®","Company":"Microsoft Corporation","CommandLine":"\\\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\\\"","CurrentDirectory":"C:\\Users\\[redacted]\\","User":"[redacted]\\[redacted]","LogonGuid":"{2B19F021-C58E-5C5A-0000-0020BBA20200}","LogonId":"0x2a2bb","TerminalSessionId":"1","IntegrityLevel":"Medium","Hashes":"SHA1=1B3B40FBC889FD4C645CC12C85D0805AC36BA254,MD5=95000560239032BC68B4C2FDFCDEF913,SHA256=D3F8FADE829D2B7BD596C4504A6DAE5C034E789B6A3DEFBE013BDA7D14466677,IMPHASH=741776AACCFC5B71FF59832DCDCACE0F","ParentProcessGuid":"{2B19F021-C58F-5C5A-0000-001026A50400}","ParentProcessId":"4960","ParentImage":"C:\\Windows\\explorer.exe","ParentCommandLine":"C:\\Windows\\Explorer.EXE"}}},"location":"EventChannel"}`

Under /var/ossec/etc/rules/local_rules.xml i have the following:

```
<group name="sysmon,">
  <rule id="255000" level="12">
     <field name="data.EventChannel.EventData.Image">\\powershell.exe</field>
     <description>Sysmon - Event 1: Bad exe</description>
     <group>sysmon_event1,powershell_execution,</group>
  </rule>
</group>
```
and the following global under ossec.conf

```
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>yes</logall>
    <logall_json>yes</logall_json>
    <email_notification>no</email_notification>
    <smtp_server>smtp.example.wazuh.com</smtp_server>
    <email_from>ossecm@example.wazuh.com</email_from>
    <email_to>recipient@example.wazuh.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <queue_size>131072</queue_size>
  </global>
```
A logtest output with the json above in archives.json is the following:

```
**Phase 2: Completed decoding.
       decoder: 'json'
       timestamp: '2019-02-07T12:07:01.801+0000'
       agent.id: '001'
       agent.name: 'redacted'
       manager.name: 'redacted'
       id: '1549541221.583932'
       full_log: '{"EventChannel":{"System":{"ProviderName":"Microsoft-Windows-Sysmon","ProviderGuid":"{5770385F-C22A-43E0-BF4C-06F5698FFBD9}","EventID":"1","Version":"5","Level":"4","Task":"1","Opcode":"0","Keywords":"0x8000000000000000","SystemTime":"2019-02-07T12:07:03.082281300Z","EventRecordID":"8587","ProcessID":"3748","ThreadID":"10972","Channel":"Microsoft-Windows-Sysmon/Operational","Computer":"redacted","SeverityValue":"INFORMATION","Message":"Process Create:"},"EventData":{"RuleName":"","UtcTime":"2019-02-07 12:07:03.077","ProcessGuid":"{2B19F021-1F67-5C5C-0000-0010001E8704}","ProcessId":"15516","Image":"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe","FileVersion":"10.0.17134.582 (WinBuild.160101.0800)","Description":"Windows PowerShell","Product":"Sistema operativo Microsoft® Windows®","Company":"Microsoft Corporation","CommandLine":"\\\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\\\"","CurrentDirectory":"[redacted]\\","User":"[redacted]","LogonGuid":"{2B19F021-C58E-5C5A-0000-0020BBA20200}","LogonId":"0x2a2bb","TerminalSessionId":"1","IntegrityLevel":"Medium","Hashes":"SHA1=1B3B40FBC889FD4C645CC12C85D0805AC36BA254,MD5=95000560239032BC68B4C2FDFCDEF913,SHA256=D3F8FADE829D2B7BD596C4504A6DAE5C034E789B6A3DEFBE013BDA7D14466677,IMPHASH=741776AACCFC5B71FF59832DCDCACE0F","ParentProcessGuid":"{2B19F021-C58F-5C5A-0000-001026A50400}","ParentProcessId":"4960","ParentImage":"C:\\Windows\\explorer.exe","ParentCommandLine":"C:\\Windows\\Explorer.EXE"}}}'
       decoder.name: 'windows_eventchannel'
       data.EventChannel.System.ProviderName: 'Microsoft-Windows-Sysmon'
       data.EventChannel.System.ProviderGuid: '{5770385F-C22A-43E0-BF4C-06F5698FFBD9}'
       data.EventChannel.System.EventID: '1'
       data.EventChannel.System.Version: '5'
       data.EventChannel.System.Level: '4'
       data.EventChannel.System.Task: '1'
       data.EventChannel.System.Opcode: '0'...[truncated]

**Phase 3: Completed filtering (rules).
       Rule id: '255000'
       Level: '12'
       Description: 'Sysmon - Event 1: Bad exe'
**Alert to be generated.
```
Anyway, it never meets alerts.json and it 's never showed in kibana. Any idea about ?
Thank you!!

**Comment by chemamartinez** [comment]
Hi @dzonespy ,

We have just found a bug in the parent rule for Sysmon events which is matching for a wrong field to get the channel. It has been fixed at this PR: https://github.com/wazuh/wazuh-ruleset/pull/285 and will be included in the next released version. Meanwhile, add the following rule on the top of the local rules file:

```
<rule id="20485" level="0" overwrite="yes">
    <if_sid>20001</if_sid>
    <field name="EventChannel.System.Channel">^Microsoft-Windows-Sysmon/Operational</field>
    <description>Sysmon - Group of events</description>
    <options>no_full_log</options>
</rule>
```

That rule will overwrite the issued rule with the correct one.

It is a bit confusing the mixing of alerts with events and what is being stored in each log file. Let me try to explain to you a couple of concepts to clarify how the manager processes the events:

- The `alerts.json` stores the generated alerts from events in JSON format (this is the feed for Elasticsearch).
- The `archives.log` contains every event coming to the Analysis engine with no modifications. This is the best file to read raw events and determine how to create custom rules and decoders.
- The `archives.json` contains the same events as the `archives.log` but events are filled with metadata as well as for the `alerts.json`. That is why the correct field to match in rules is `EventChannel.EventData.Image` instead of `data.EventChannel.EventData.Image`. The `data` structure contains fields which have already been extracted.

So, the rule you need is the same as I told you before:

```
<rule id="255000" level="12">
     <if_group>sysmon_event1</if_group>
     <field name="EventChannel.EventData.Image">\powershell.exe||\.ps1||\.ps2</field>
     <description>Sysmon - Event 1: Bad exe: $(EventChannel.EventData.Image)</description>
     <group>sysmon_event1,powershell_execution,</group>
</rule>
```

Thank you for reporting this. Let me know if it works for you.

Best regards,
Chema.

**Comment by dzonespy** [comment]
Hi @chemamartinez , thank for your amazing support and explanation (only 2 days working on wazuh from my side ;) ). Unfortunately, it seems i ve still no way to get sysmon events over dashboard (and not even under alerts.json). This is my /var/ossec/etc/rules/local_rules.xml:

```
<group name="sysmon,">

  <rule id="20485" level="0" overwrite="yes">
    <if_sid>20001</if_sid>
    <field name="EventChannel.System.Channel">^Microsoft-Windows-Sysmon/Operational</field>
    <description>Sysmon - Group of events</description>
    <options>no_full_log</options>
</rule>

<rule id="255000" level="12">
     <if_group>sysmon_event1</if_group>
     <field name="EventChannel.EventData.Image">\\powershell.exe</field>
     <description>Sysmon - Event 1: Bad exe: $(EventChannel.EventData.Image)</description>
     <group>sysmon_event1,powershell_execution,</group>
</rule>

</group>
```

The log under /var/ossec/logs/archives/archives.log when triggering a Powershell Process Create event from client agent:

`2019 Feb 07 14:39:01 (...redacted...) any->EventChannel {"EventChannel":{"System":{"ProviderName":"Microsoft-Windows-Sysmon","ProviderGuid":"{5770385F-C22A-43E0-BF4C-06F5698FFBD9}","EventID":"1","Version":"5","Level":"4","Task":"1","Opcode":"0","Keywords":"0x8000000000000000","SystemTime":"2019-02-07T14:39:00.609519800Z","EventRecordID":"12450","ProcessID":"3748","ThreadID":"10972","Channel":"Microsoft-Windows-Sysmon/Operational","Computer":"redacted","SeverityValue":"INFORMATION","Message":"Process Create:"},"EventData":{"RuleName":"","UtcTime":"2019-02-07 14:39:00.603","ProcessGuid":"{2B19F021-4304-5C5C-0000-0010B18DD305}","ProcessId":"19124","Image":"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe","FileVersion":"10.0.17134.582 (WinBuild.160101.0800)","Description":"Windows PowerShell","Product":"Sistema operativo Microsoft® Windows®","Company":"Microsoft Corporation","CommandLine":"\\\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\\\"","CurrentDirectory":"C:\\Users\\redacted\\","User":"redacted\\redacted","LogonGuid":"{2B19F021-C58E-5C5A-0000-0020BBA20200}","LogonId":"0x2a2bb","TerminalSessionId":"1","IntegrityLevel":"Medium","Hashes":"SHA1=1B3B40FBC889FD4C645CC12C85D0805AC36BA254,MD5=95000560239032BC68B4C2FDFCDEF913,SHA256=D3F8FADE829D2B7BD596C4504A6DAE5C034E789B6A3DEFBE013BDA7D14466677,IMPHASH=741776AACCFC5B71FF59832DCDCACE0F","ParentProcessGuid":"{2B19F021-C58F-5C5A-0000-001026A50400}","ParentProcessId":"4960","ParentImage":"C:\\Windows\\explorer.exe","ParentCommandLine":"C:\\Windows\\Explorer.EXE"}}}`

very frustrating for me. May be at this point i ve something wrong in other places of wazuh installation ?

**Comment by chemamartinez** [comment]
Hi @dzonespy ,

You are welcome! Don't worry about that. I know is a little bit tricky to deal with custom rules first times.

I know this may sound a little bit obvious, but, have you restarted the manager after the changes to load the new rules? It has to be restarted to load new configuration and rules.

You can do it by running `systemctl restart wazuh-manager`.

If yes, we have to continue investigating this deeper.

**Comment by dzonespy** [comment]
Hi, i usually use /var/ossec/bin/ossec-control restart to apply new rules.
Anyway, still no luck. Some other suggestions in order to guide me in checking something else ?

**Comment by dzonespy** [comment]
Hello @chemamartinez, i would to thank you for your amazing support! Applying new rules, it works!
Thank you again!

**Comment by chemamartinez** [comment]
Hi @dzonespy ,

I am glad to hear it is working for you now!

Thank you as well for the feedback. As it is solved now, let me close this thread. Anyway, if you need further assistance don't hesitate to reopen it.

Best regards,
Chema.
