### ISSUE TITLE
windows decoders won't pick correct account name for account lockout messages

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-ruleset#52]
Sample log message

```text
2017 Jun 10 12:34:01 WinEvtLog: Security: AUDIT_SUCCESS(4740): 
Microsoft-Windows-Security-Auditing: (no user): no domain: SERVER.mydomain.local: 0x8000000000000000    
message: A user account was locked out.  
Subject:  
Security ID:  S-1-5-18  
Account Name:  SERVER$  
Account Domain:  MYDOMAIN  
Logon ID:  0x3e7  
Account That Was Locked Out:  Security ID:  S-1-5-21-1634102539-605432415-635521153-12345  Account Name:  user_account_name  Additional Information:  Caller Computer Name: OTHERSERVER
```

I've broken the message into multiple lines for readability.   
Since the `account_name` is extracted by matching `Account Name: xxxx`, and there are two instances, only the first one is picked up. In this message that doesn't correspond to the account that was locked out.

**Comment by jesuslinares** [comment]
It will be fixed ASAP.

Thanks!

**Comment by jesuslinares** [comment]
Hi @rossengeorgiev,

it is fixed https://github.com/wazuh/wazuh-ruleset/commit/75014560e457d6e3b60576750c415b7ceec73edf. According to the [Windows documentation](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventID=4625), the first fields (Security ID, Account Name, Account Domain, Logon ID) are part of "Subject". So, they are extracted as: `subject.field_name`. In addition, now we extract the _type_ of event and the _logon type_.

Example:

```
2017 Apr 18 17:30:52 WinEvtLog: Security: AUDIT_FAILURE(4625): Microsoft-Windows-Security-Auditing: (no user): no domain: WIN-1: An account failed to log on. Subject: Security ID: S-1-5-10 Account Name: WIN-1$ Account Domain: WORKGROUP Logon ID: 0x3E7 Logon Type: 10 Account For Which Logon Failed: Security ID: S-1-0-0 Account Name: Santiago Account Domain: test2 Failure Information: Failure Reason: Unknown user name or bad password. Status: 0xC000006D Sub Status: 0xC0000064 Process Information: Caller Process ID: 0xb50 Caller Process Name: C:\Windows\System32\winlogon.exe Network Information: Workstation Name: WIN-1 Source Network Address: 17.217.25.247 Source Port: 0 Detailed Authentication Information: Logon Process: User32 Authentication Package: Negotiate Transited Services: - Package Name (NTLM only): - Key Length: 0 This event is generated when a logon request fails. It.


**Phase 1: Completed pre-decoding.
       full event: '2017 Apr 18 17:30:52 WinEvtLog: Security: AUDIT_FAILURE(4625): Microsoft-Windows-Security-Auditing: (no user): no domain: WIN-1: An account failed to log on. Subject: Security ID: S-1-5-10 Account Name: WIN-1$ Account Domain: WORKGROUP Logon ID: 0x3E7 Logon Type: 10 Account For Which Logon Failed: Security ID: S-1-0-0 Account Name: Santiago Account Domain: test2 Failure Information: Failure Reason: Unknown user name or bad password. Status: 0xC000006D Sub Status: 0xC0000064 Process Information: Caller Process ID: 0xb50 Caller Process Name: C:\Windows\System32\winlogon.exe Network Information: Workstation Name: WIN-1 Source Network Address: 17.217.25.247 Source Port: 0 Detailed Authentication Information: Logon Process: User32 Authentication Package: Negotiate Transited Services: - Package Name (NTLM only): - Key Length: 0 This event is generated when a logon request fails. It.'
       hostname: 'ip-10-0-0-10'
       program_name: 'WinEvtLog'
       log: 'Security: AUDIT_FAILURE(4625): Microsoft-Windows-Security-Auditing: (no user): no domain: WIN-1: An account failed to log on. Subject: Security ID: S-1-5-10 Account Name: WIN-1$ Account Domain: WORKGROUP Logon ID: 0x3E7 Logon Type: 10 Account For Which Logon Failed: Security ID: S-1-0-0 Account Name: Santiago Account Domain: test2 Failure Information: Failure Reason: Unknown user name or bad password. Status: 0xC000006D Sub Status: 0xC0000064 Process Information: Caller Process ID: 0xb50 Caller Process Name: C:\Windows\System32\winlogon.exe Network Information: Workstation Name: WIN-1 Source Network Address: 17.217.25.247 Source Port: 0 Detailed Authentication Information: Logon Process: User32 Authentication Package: Negotiate Transited Services: - Package Name (NTLM only): - Key Length: 0 This event is generated when a logon request fails. It.'

**Phase 2: Completed decoding.
       decoder: 'windows'
       type: 'Security'
       status: 'AUDIT_FAILURE'
       id: '4625'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: '(no user)'
       system_name: 'WIN-1'
       subject.security_id: 'S-1-5-10'
       subject.account_name: 'WIN-1$'
       subject.account_domain: 'WORKGROUP'
       subject.logon_id: '0x3E7'
       account_name: 'Santiago'
       account_domain: 'test2'
       logon_type: '10'
       srcip: '17.217.25.247'

**Phase 3: Completed filtering (rules).
       Rule id: '18130'
       Level: '5'
       Description: 'Windows: Logon Failure - Unknown user or bad password.'
       Info - Link: 'http://www.ultimatewindowssecurity.com/events/com190.html'
**Alert to be generated.
```

Thanks for the feedback.

**Comment by rossengeorgiev** [comment]
Awesome! Shouldn't the rule matching be `18116` tho?

**Comment by jesuslinares** [comment]
The event 4625 corresponds to the rule 18130: https://github.com/wazuh/wazuh-ruleset/blob/master/rules/0220-msauth_rules.xml#L199

The rule 18116 is for events with id 644 or 4740: https://github.com/wazuh/wazuh-ruleset/blob/master/rules/0220-msauth_rules.xml#L126

Regards.

**Comment by rossengeorgiev** [comment]
Oh I see, you've used a different message. Still doesn't work for 4740.

```text
2017 Jun 10 12:34:01 WinEvtLog: Security: AUDIT_SUCCESS(4740): Microsoft-Windows-Security-Auditing: (no user): no domain: SERVER.mydomain.local: 0x8000000000000000    message: A user account was locked out.  Subject:  Security ID:  S-1-5-18  Account Name:  SERVER$  Account Domain:  MYDOMAIN  Logon ID:  0x3e7  Account That Was Locked Out:  Security ID:  S-1-5-21-1634102539-605432415-635521153-12345  Account Name:  user_account_name  Additional Information:  Caller Computer Name: OTHERSERVER


**Phase 1: Completed pre-decoding.
       full event: '2017 Jun 10 12:34:01 WinEvtLog: Security: AUDIT_SUCCESS(4740): Microsoft-Windows-Security-Auditing: (no user): no domain: SERVER.mydomain.local: 0x8000000000000000    message: A user account was locked out.  Subject:  Security ID:  S-1-5-18  Account Name:  SERVER$  Account Domain:  MYDOMAIN  Logon ID:  0x3e7  Account That Was Locked Out:  Security ID:  S-1-5-21-1634102539-605432415-635521153-12345  Account Name:  user_account_name  Additional Information:  Caller Computer Name: OTHERSERVER'
       hostname: 'wazuh-vm'
       program_name: 'WinEvtLog'
       log: 'Security: AUDIT_SUCCESS(4740): Microsoft-Windows-Security-Auditing: (no user): no domain: SERVER.mydomain.local: 0x8000000000000000    message: A user account was locked out.  Subject:  Security ID:  S-1-5-18  Account Name:  SERVER$  Account Domain:  MYDOMAIN  Logon ID:  0x3e7  Account That Was Locked Out:  Security ID:  S-1-5-21-1634102539-605432415-635521153-12345  Account Name:  user_account_name  Additional Information:  Caller Computer Name: OTHERSERVER'

**Phase 2: Completed decoding.
       decoder: 'windows'
       type: 'Security'
       status: 'AUDIT_SUCCESS'
       id: '4740'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: '(no user)'
       system_name: 'SERVER.mydomain.local'
       account_name: 'SERVER$'
       account_domain: 'MYDOMAIN'

**Phase 3: Completed filtering (rules).
       Rule id: '18116'
       Level: '9'
       Description: 'Windows: User account locked out (multiple login errors).'
**Alert to be generated.

**Comment by jesuslinares** [comment]
Review it.

**Comment by jesuslinares** [comment]
I missed a space after "Subject". It is fixed: https://github.com/wazuh/wazuh-ruleset/commit/318087ead164232581f3099308f77d1ee49954f5

Also, I extract the SID and the computer:

```
2017 Jun 10 12:34:01 WinEvtLog: Security: AUDIT_SUCCESS(4740): Microsoft-Windows-Security-Auditing: (no user): no domain: SERVER.mydomain.local: 0x8000000000000000    message: A user account was locked out.  Subject:  Security ID:  S-1-5-18  Account Name:  SERVER$  Account Domain:  MYDOMAIN  Logon ID:  0x3e7  Account That Was Locked Out:  Security ID:  S-1-5-21-1634102539-605432415-635521153-12345  Account Name:  user_account_name  Additional Information:  Caller Computer Name: OTHERSERVER


**Phase 1: Completed pre-decoding.
       full event: '2017 Jun 10 12:34:01 WinEvtLog: Security: AUDIT_SUCCESS(4740): Microsoft-Windows-Security-Auditing: (no user): no domain: SERVER.mydomain.local: 0x8000000000000000    message: A user account was locked out.  Subject:  Security ID:  S-1-5-18  Account Name:  SERVER$  Account Domain:  MYDOMAIN  Logon ID:  0x3e7  Account That Was Locked Out:  Security ID:  S-1-5-21-1634102539-605432415-635521153-12345  Account Name:  user_account_name  Additional Information:  Caller Computer Name: OTHERSERVER'
       hostname: 'ip-10-0-0-10'
       program_name: 'WinEvtLog'
       log: 'Security: AUDIT_SUCCESS(4740): Microsoft-Windows-Security-Auditing: (no user): no domain: SERVER.mydomain.local: 0x8000000000000000    message: A user account was locked out.  Subject:  Security ID:  S-1-5-18  Account Name:  SERVER$  Account Domain:  MYDOMAIN  Logon ID:  0x3e7  Account That Was Locked Out:  Security ID:  S-1-5-21-1634102539-605432415-635521153-12345  Account Name:  user_account_name  Additional Information:  Caller Computer Name: OTHERSERVER'

**Phase 2: Completed decoding.
       decoder: 'windows'
       type: 'Security'
       status: 'AUDIT_SUCCESS'
       id: '4740'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: '(no user)'
       system_name: 'SERVER.mydomain.local'
       subject.security_id: 'S-1-5-18'
       subject.account_name: 'SERVER$'
       subject.account_domain: 'MYDOMAIN'
       subject.logon_id: '0x3e7'
       security_id: 'S-1-5-21-1634102539-605432415-635521153-12345'
       account_name: 'user_account_name'
       caller_computer: 'OTHERSERVER'

**Phase 3: Completed filtering (rules).
       Rule id: '18116'
       Level: '9'
       Description: 'Windows: User account locked out (multiple login errors).'
**Alert to be generated.
```

Thanks for helping us with Windows logs. We are looking for the way to decode these kind of events automatically.

Regards.

**Comment by rossengeorgiev** [comment]
Awesome, it works! Thank you
